version: "3.8"

services:
  kasa-app:
    container_name: kasa-dev
    image: kasa-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/workflow/kasa-app"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true 
