version: "3.8"

services:
  kasa-app:
    container_name: kasa-app
    image: kasa-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/kasa-app"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true 
